//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCiv1.UI {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBoxResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBoxResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenCiv1.UI.MessageBox.MessageBoxResources", typeof(MessageBoxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Information_64 {
            get {
                object obj = ResourceManager.GetObject("Information_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Question_64 {
            get {
                object obj = ResourceManager.GetObject("Question_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Stop_64 {
            get {
                object obj = ResourceManager.GetObject("Stop_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Warning_64 {
            get {
                object obj = ResourceManager.GetObject("Warning_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
