using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenCiv1
{
	public enum TechnologyEnum
	{
		None = -1,
		Alphabet = 0,
		CodeOfLaws = 1,
		Currency = 2,
		AtomicTheory = 3,
		Democracy = 4,
		Monarchy = 5,
		Astronomy = 6,
		Mapmaking = 7,
		Navigation = 8,
		Mathematics = 9,
		Medicine = 10,
		Physics = 11,
		Engineering = 12,
		University = 13,
		Magnetism = 14,
		Electronics = 15,
		Masonry = 16,
		BronzeWorking = 17,
		IronWorking = 18,
		BridgeBuilding = 19,
		Invention = 20,
		Computers = 21,
		Writing = 22,
		SteamEngine = 23,
		Trade = 24,
		CeremonialBurial = 25,
		Mysticism = 26,
		NuclearFission = 27,
		Philosophy = 28,
		Religion = 29,
		Literacy = 30,
		HorsebackRiding = 31,
		Feudalism = 32,
		TheWheel = 33,
		Gunpowder = 34,
		Industrialization = 35,
		Chemistry = 36,
		Combustion = 37,
		Flight = 38,
		AdvancedFlight = 39,
		SpaceFlight = 40,
		MassProduction = 41,
		Pottery = 42,
		Communism = 43,
		TheRepublic = 44,
		Construction = 45,
		Rocketry = 46,
		TheCorporation = 47,
		Metallurgy = 48,
		Railroad = 49,
		NuclearPower = 50,
		TheoryOfGravity = 51,
		Steel = 52,
		Banking = 53,
		Electricity = 54,
		Refining = 55,
		Explosives = 56,
		Superconductor = 57,
		Automobile = 58,
		GeneticEngineering = 59,
		Plastics = 60,
		Recycling = 61,
		Chivalry = 62,
		Robotics = 63,
		Conscription = 64,
		LaborUnion = 65,
		FusionPower = 66
	}
}
